"""init create tables

Revision ID: fa6f4afaf609
Revises: 
Create Date: 2023-06-07 11:31:59.763332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f4afaf609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Integer(), nullable=False),
    sa.Column('dislike', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_channel_id'), 'answers', ['channel_id'], unique=False)
    op.create_index(op.f('ix_answers_guild_id'), 'answers', ['guild_id'], unique=False)
    op.create_index(op.f('ix_answers_member_id'), 'answers', ['member_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('channel_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_type', sa.Enum('POST', 'QUESTION', 'CHAT', name='channeltype'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configs_channel_id'), 'channel_configs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_configs_guild_id'), 'channel_configs', ['guild_id'], unique=False)
    op.create_table('questions',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_channel_id'), 'questions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_questions_guild_id'), 'questions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_questions_member_id'), 'questions', ['member_id'], unique=False)
    op.create_table('score_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('score_src', sa.Enum('POST', 'POST_REACTION', 'QUESTION', 'ANSWER', 'ANSWER_REACTION', 'CHAT', 'CHAT_REACTION', name='scoresource'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_configs_channel_id'), 'score_configs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_score_configs_guild_id'), 'score_configs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_score_configs_score'), 'score_configs', ['score'], unique=False)
    op.create_index(op.f('ix_score_configs_score_src'), 'score_configs', ['score_src'], unique=False)
    op.create_table('user_scores',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('score_type', sa.Enum('POST', 'QUESTION', 'CHAT', name='scoretype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scores_guild_id'), 'user_scores', ['guild_id'], unique=False)
    op.create_index(op.f('ix_user_scores_member_id'), 'user_scores', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_scores_score_type'), 'user_scores', ['score_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scores_score_type'), table_name='user_scores')
    op.drop_index(op.f('ix_user_scores_member_id'), table_name='user_scores')
    op.drop_index(op.f('ix_user_scores_guild_id'), table_name='user_scores')
    op.drop_table('user_scores')
    op.drop_index(op.f('ix_score_configs_score_src'), table_name='score_configs')
    op.drop_index(op.f('ix_score_configs_score'), table_name='score_configs')
    op.drop_index(op.f('ix_score_configs_guild_id'), table_name='score_configs')
    op.drop_index(op.f('ix_score_configs_channel_id'), table_name='score_configs')
    op.drop_table('score_configs')
    op.drop_index(op.f('ix_questions_member_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_guild_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_channel_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_channel_configs_guild_id'), table_name='channel_configs')
    op.drop_index(op.f('ix_channel_configs_channel_id'), table_name='channel_configs')
    op.drop_table('channel_configs')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_member_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_guild_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_channel_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
