"""add score_logs table

Revision ID: 5df712964956
Revises: f3061e8f8bba
Create Date: 2023-06-15 17:41:36.099603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df712964956'
down_revision = 'f3061e8f8bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_logs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('score_src', sa.Enum('POST', 'POST_REACTION', 'QUESTION', 'ANSWER', 'ANSWER_REACTION', 'CHAT', 'CHAT_REACTION', name='scoresource'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_logs_channel_id'), 'score_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_score_logs_guild_id'), 'score_logs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_score_logs_member_id'), 'score_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_score_logs_score_src'), 'score_logs', ['score_src'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_logs_score_src'), table_name='score_logs')
    op.drop_index(op.f('ix_score_logs_member_id'), table_name='score_logs')
    op.drop_index(op.f('ix_score_logs_guild_id'), table_name='score_logs')
    op.drop_index(op.f('ix_score_logs_channel_id'), table_name='score_logs')
    op.drop_table('score_logs')
    # ### end Alembic commands ###
