"""add cooldown to score_configs

Revision ID: f3061e8f8bba
Revises: fa6f4afaf609
Create Date: 2023-06-15 11:19:30.194262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3061e8f8bba'
down_revision = 'fa6f4afaf609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_configs', sa.Column('cooldown', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_configs', 'cooldown')
    # ### end Alembic commands ###
